export const leaderDetailSelect = {
  id: true,
  realName: true,
  nickname: true,
  phone: true,
  region: true,
  residentLocation: true,
  status: true,
  level: true,
  externalLeaderId: true,
  miniProgramLeaderId: true,
  miniProgramPhone: true,
  rawLeaderIdentity: true,
  rawLeaderLevel: true,
  rawJobStatus: true,
  leadCount: true,
  leadDays: true,
  auditTime: true,
  frozenTime: true,
  jobStatus: true,
  lastImportedAt: true,
  sourceSystem: true,
  joinDate: true,
  recommenderLeaderId: true,
  tags: true,
  remark: true,
  createdAt: true,
  updatedAt: true,
  user: {
    select: {
      id: true,
      username: true,
      name: true,
      role: true,
      status: true,
    },
  },
  recommenderLeader: {
    select: {
      id: true,
      realName: true,
      nickname: true,
      phone: true,
      status: true,
    },
  },
} as const;
